apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-test-app
  labels:
    app: my-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-test-app
  template:
    metadata:
      labels:
        app: my-test-app
    spec:
      containers:
      - name: simple-node
        image: erikbaer/simple-node
        ports:
        - containerPort: 80